### ISSUE TITLE
No clear license

### ISSUE THREAD

**Issue by ilzolende** [fvsch/monospace-theme#2]
You mention [here](https://monospace-theme.tumblr.com/post/96646019055/monospace-theme-features) that your theme is free/gratis, but I can't tell what that means for people who want to reuse parts of your theme for other projects. (It is a pretty theme!)

**Comment by fvsch** [comment]
Hi. Thanks for the heads up. I’ve added a license, more specifically the WTFPL (same as the [ReMarkdown](https://github.com/fvsch/remarkdown) project used in this theme).
